CREATE TABLE LIVRO(
ID_LIVRO NUMBER PRIMARY KEY NOT NULL,
TITULO VARCHAR2(255) NOT NULL,
AUTOR VARCHAR2(255) NOT NULL,
EDITORA VARCHAR2(255) NOT NULL,
NR_PAGINAS NUMBER,
FORMATO CHAR(1), --1 para brochura e 2 para capa_dura
IDIOMA CHAR(1), --1 para português, 2 para inglês e 3 para espanhol
STATUS_LIVRO CHAR(1) NOT NULL --1 para disponível e 2 para indisponível
);

CREATE SEQUENCE SEQ_LIVRO
START WITH 1
INCREMENT BY 1
nocache
nocycle;

CREATE TABLE CLIENTE(
ID_CLIENTE NUMBER PRIMARY KEY NOT NULL,
NOME VARCHAR(255) NOT NULL,
TELEFONE VARCHAR(20),
EMAIL VARCHAR(255),
STATUS_CLIENTE CHAR(1), --1 para ativo, 2 para bloqueado e 3 para cancelado
TIPO_CLIENTE CHAR(1) --1 para comum e 2 para premium
);

CREATE SEQUENCE SEQ_CLIENTE
START WITH 1
INCREMENT BY 1
nocache
nocycle;

CREATE TABLE FUNCIONARIO(
ID_FUNCIONARIO NUMBER PRIMARY KEY NOT NULL,
NOME VARCHAR(255) NOT NULL,
TELEFONE VARCHAR2(255),
EMAIL VARCHAR2(255) NOT NULL
);

CREATE SEQUENCE SEQ_FUNCIONARIO
START WITH 1
INCREMENT BY 1
nocache
nocycle;

CREATE TABLE EMPRESTIMO(
ID_EMPRESTIMO NUMBER PRIMARY KEY NOT NULL,
ID_LIVRO NUMBER NOT NULL,
ID_CLIENTE NUMBER NOT NULL,
ID_FUNCIONARIO NUMBER NOT NULL,
CONSTRAINT FK_ID_LIVRO FOREIGN KEY (ID_LIVRO) REFERENCES LIVRO (ID_LIVRO),
CONSTRAINT FK_ID_CLIENTE FOREIGN KEY (ID_CLIENTE) REFERENCES CLIENTE (ID_CLIENTE),
CONSTRAINT FK_ID_FUNCIONARIO FOREIGN KEY (ID_FUNCIONARIO) REFERENCES FUNCIONARIO (ID_FUNCIONARIO)
);

CREATE SEQUENCE SEQ_EMPRESTIMO
START WITH 1
INCREMENT BY 1
nocache
nocycle;

INSERT INTO LIVRO (ID_LIVRO, TITULO, AUTOR, EDITORA, NR_PAGINAS, FORMATO, IDIOMA, STATUS_LIVRO)
VALUES (SEQ_LIVRO.NEXTVAL, 'Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 'Rocco', null, 1, 1, 1)

INSERT INTO LIVRO (ID_LIVRO, TITULO, AUTOR, EDITORA, NR_PAGINAS, FORMATO, IDIOMA, STATUS_LIVRO)
VALUES (SEQ_LIVRO.NEXTVAL, 'Harry Potter e a Camâra Secreta', 'J.K. Rowling', 'Rocco', null, 1, 1, 1)

INSERT INTO LIVRO (ID_LIVRO, TITULO, AUTOR, EDITORA, NR_PAGINAS, FORMATO, IDIOMA, STATUS_LIVRO)
VALUES (SEQ_LIVRO.NEXTVAL, 'Harry Potter e o Prisioneiro de Azkaban', 'J.K. Rowling', 'Rocco', null, 1, 1, 1)

INSERT INTO LIVRO (ID_LIVRO, TITULO, AUTOR, EDITORA, NR_PAGINAS, FORMATO, IDIOMA, STATUS_LIVRO)
VALUES (SEQ_LIVRO.NEXTVAL, 'Harry Potter e o Cálice de Fogo', 'J.K. Rowling', 'Rocco', null, 1, 1, 1)

INSERT INTO LIVRO (ID_LIVRO, TITULO, AUTOR, EDITORA, NR_PAGINAS, FORMATO, IDIOMA, STATUS_LIVRO)
VALUES (SEQ_LIVRO.NEXTVAL, 'Harry Potter e a Ordem Da Fênix', 'J.K. Rowling', 'Rocco', null, 1, 1, 1)

INSERT INTO LIVRO (ID_LIVRO, TITULO, AUTOR, EDITORA, NR_PAGINAS, FORMATO, IDIOMA, STATUS_LIVRO)
VALUES (SEQ_LIVRO.NEXTVAL, 'Harry Potter e o Príncipe Mestiço', 'J.K. Rowling', 'Rocco', null, 1, 1, 1)

INSERT INTO LIVRO (ID_LIVRO, TITULO, AUTOR, EDITORA, NR_PAGINAS, FORMATO, IDIOMA, STATUS_LIVRO)
VALUES (SEQ_LIVRO.NEXTVAL, 'Harry Potter e as Relíquias da Morte', 'J.K. Rowling', 'Rocco', null, 1, 1, 1)

INSERT INTO CLIENTE (ID_CLIENTE, NOME, TELEFONE, EMAIL, STATUS_CLIENTE, TIPO_CLIENTE)
VALUES (SEQ_CLIENTE.NEXTVAL, 'Bianca Marostica', '519813251654', null, '1', '1')

INSERT INTO CLIENTE (ID_CLIENTE, NOME, TELEFONE, EMAIL, STATUS_CLIENTE, TIPO_CLIENTE)
VALUES (SEQ_CLIENTE.NEXTVAL, 'Marcelo Ungaretti', '51935486546', null, '1', '1')

INSERT INTO CLIENTE (ID_CLIENTE, NOME, TELEFONE, EMAIL, STATUS_CLIENTE, TIPO_CLIENTE)
VALUES (SEQ_CLIENTE.NEXTVAL, 'David Salles', '61997316648', null, '1', '1')

INSERT INTO FUNCIONARIO (ID_FUNCIONARIO, NOME, TELEFONE, EMAIL)
VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Juvenal Juvencio', '5134834458', 'juvenal@hotmail.com')

INSERT INTO FUNCIONARIO (ID_FUNCIONARIO, NOME, TELEFONE, EMAIL)
VALUES (SEQ_FUNCIONARIO.NEXTVAL, 'Florentina de Jesus', '5134423166', 'florentina@hotmail.com')

INSERT INTO EMPRESTIMO (ID_EMPRESTIMO, ID_LIVRO, ID_CLIENTE, ID_FUNCIONARIO)
VALUES (SEQ_EMPRESTIMO.NEXTVAL, 1 , 1 , 1 )

INSERT INTO EMPRESTIMO (ID_EMPRESTIMO, ID_LIVRO, ID_CLIENTE, ID_FUNCIONARIO)
VALUES (SEQ_EMPRESTIMO.NEXTVAL, 5 , 3 , 1 )

INSERT INTO EMPRESTIMO (ID_EMPRESTIMO, ID_LIVRO, ID_CLIENTE, ID_FUNCIONARIO)
VALUES (SEQ_EMPRESTIMO.NEXTVAL, 4 , 2 , 2 )


SELECT * FROM LIVRO
SELECT * FROM CLIENTE
SELECT * FROM FUNCIONARIO
SELECT * FROM EMPRESTIMO
